# Generated by Django 4.1.1 on 2022-09-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.IntegerField(choices=[(1, 'Applied'), (2, 'Accepted'), (3, 'Rejected')], default=1),
        ),
    ]
