# Generated by Django 4.1.1 on 2022-09-10 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_candidate_dateapplied_candidate_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
    ]
