# Generated by Django 4.1.1 on 2022-09-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_candidate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='experience',
            new_name='yearsOfExperience',
        ),
        migrations.AddField(
            model_name='candidate',
            name='salary',
            field=models.IntegerField(default=23000),
            preserve_default=False,
        ),
    ]
