# Generated by Django 4.1.1 on 2022-09-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_experience_candidate_yearsofexperience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default='+91 7026521395', max_length=255),
            preserve_default=False,
        ),
    ]
