# Generated by Django 4.1.1 on 2022-09-11 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_candidate_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='resume',
        ),
    ]
