# Generated by Django 4.1.1 on 2022-09-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_candidate_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(default='dfdf', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
