# Generated by Django 4.1.1 on 2022-09-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_candidate_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='yearsOfExperience',
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(default='hi i have some experience', max_length=255),
            preserve_default=False,
        ),
    ]
