# Generated by Django 4.1.1 on 2022-09-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_candidate_yearsofexperience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.CharField(default='sdfds', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.CharField(default='sdfsd', max_length=255),
            preserve_default=False,
        ),
    ]
